name: Build application

on:
  push:

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
